Repository ace-ecosystem/ace2-ams-gui, pull requests merged in 2021-10, with the labels that each got.

#5 ESLint and Prettier fixes
  .devcontainer/devcontainer.json
  .eslintrc.js
  .github/workflows/main.yml
  .gitignore
  .prettierignore
  .prettierrc.json
  Dockerfile.dev
  README.md
  bin/format-code.sh
  docker-compose.yml
  mkdocs.yml
  models/alert.ts
  models/node.ts
  models/user.ts
  package-lock.json
  package.json
  services/api/alerts.ts
  services/api/axios.ts
  services/api/base.ts
  services/api/users.ts
  src/App.vue
  src/components/Alerts/TheAlertActionToolbar.vue
  src/components/Alerts/TheAlertsTable.vue
  src/components/Filters/TheFilterToolbar.vue
  src/components/Modals/AssignModal.vue
  src/components/Modals/BaseModal.vue
  src/components/Modals/CommentModal.vue
  src/components/Modals/DeleteModal.vue
  src/components/Modals/DispositionModal.vue
  src/components/Modals/FilterModal.vue
  src/components/Modals/RemediateModal.vue
  src/components/Modals/SaveToEventModal.vue
  src/components/Modals/TagModal.vue
  src/components/UserInterface/TheHeader.vue
  src/main.ts
  src/pages/Alerts/ManageAlerts.vue
  src/shims-vue.d.ts
  src/store/alerts.ts
  src/store/index.ts
  src/store/selectedAlerts.ts
  src/store/users.ts
  tests/e2e/specs/ManageAlerts.js
  tests/unit/ManageAlerts.spec.ts
  tests/unit/TheAlertActionToolbar.spec.ts
  tests/unit/TheAlertsTable.spec.ts
  tests/unit/TheHeader.spec.ts
  tsconfig.json
  vue.config.js
Labels: enhancement

#8 Frontend Tests
  .dockerignore
  .jest/setEnvVars.js
  jest.config.js
  package.json
  services/api/base.ts
  services/api/users.ts
  src/components/Alerts/TheAlertsTable.vue
  src/components/Filters/TheFilterToolbar.vue
  src/components/Modals/AssignModal.vue
  src/components/Modals/BaseModal.vue
  src/components/Modals/DispositionModal.vue
  src/components/Modals/SaveToEventModal.vue
  src/store/alerts.ts
  src/store/selectedAlerts.ts
  src/store/users.ts
  tests/unit/services/api/alerts.spec.ts
  tests/unit/services/api/base.spec.ts
  tests/unit/services/api/nock.ts
  tests/unit/services/api/users.spec.ts
  tests/unit/src/components/AssignModal.spec.ts
  tests/unit/src/components/ManageAlerts.spec.ts
  tests/unit/src/components/TheAlertActionToolbar.spec.ts
  tests/unit/src/components/TheAlertsTable.spec.ts
  tests/unit/src/components/TheHeader.spec.ts
  tests/unit/src/components/mockStore.ts
  tests/unit/src/store/alerts.spec.ts
  tests/unit/src/store/modals.spec.ts
  tests/unit/src/store/selectedAlerts.spec.ts
  tests/unit/src/store/users.spec.ts
Labels: enhancement

#9 Cypress + Documentation
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/main.yml
  cypress.json
  docs/development/index.md
  docs/development/open-in-container.png
  docs/development/terminal.png
  docs/development/test-runner.png
  package-lock.json
  package.json
  tests/e2e/plugins/index.js
  tests/e2e/specs/ManageAlerts.spec.js
Labels: documentation, enhancement

#10 Fixes docs formatting
  docs/development/index.md
Labels: documentation

#11 Removes docker-compose configuration
  .devcontainer/Dockerfile
  Dockerfile
  Dockerfile.dev
  README.md
  docker-compose.yml
  docs/development/index.md
Labels: documentation, enhancement

#14 Adds missing WSL 2 docs for opening VSCode
  docs/development/index.md
Labels: documentation
